---
# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Values file for deploying SEBA with Ponsim
# Use this file to deploy the service versions speecified in the Helm charts.

# onos
images:
  onos:
    repository: 'dmoro92/onos'
    tag: '2.2-demo'
    pullPolicy: Always
  mininet:
#    repository: 'opennetworking/mn-stratum'
# The `opennetworking/mn-stratum` image misses `bridge-utils` and `dnsmasq`
# package, which causes an error when `/toposcripts/topo_mn_stratum.py` tries
# to build LinuxBridge with `brctl` command.
    repository: 'steven30801/mn-stratum'
    tag: 'latest'
    pullPolicy: Always

# voltha
etcd-cluster:
  clusterSize: 1

# in workflow/att-workflow service chart
att-workflow-driver:
  image:
    tag: 'master'
  # this is mandatory, it's needed to correctly configure the kafka endpoint
  kafkaService: cord-kafka

# in workflow/tt-workflow service chart
tt-workflow-driver:
  image:
    repository: andybavier/test-image-synchronizer
    tag: tt-workflow-driver

  # this is mandatory, it's needed to correctly configure the kafka endpoint
  kafkaService: cord-kafka

# in mininet chart
# FIXME: is multicast working?
enableMulticast: False
topoScript: '/toposcripts/topo_mn_stratum.py'

# in ponsim-pod chart
bandwidthProfiles: True
legacyPonsim: False

# ONOS applications
sadisAppUrl: "http://10.128.22.1:30160/sadis-app-4.0.0-SNAPSHOT.oar"
sadisAppVersion: "4.0.0.SNAPSHOT"

dhcpl2relayAppUrl: "http://10.128.22.1:30160/dhcpl2relay-app-2.0.0-SNAPSHOT.oar"
dhcpl2relayAppVersion: "2.0.0.SNAPSHOT"

oltAppUrl: "http://10.128.22.1:30160/olt-app-4.0.0-SNAPSHOT.oar"
oltAppVersion: "4.0.0.SNAPSHOT"

kafkaAppUrl: "http://10.128.22.1:30160/kafka-2.0.0-SNAPSHOT.oar"
kafkaAppVersion: "2.0.0.SNAPSHOT"

aaaAppUrl: "http://10.128.22.1:30160/aaa-app-2.0.0-SNAPSHOT.oar"
aaaAppVersion: "2.0.0.SNAPSHOT"

# fabric
fabric:
  enabled: true
  # Whether the fabric uses Stratum or not, and the corresponding ONOS apps
  # required to control the switch.
  stratum:
    enabled: true
    driverAppId: "org.onosproject.drivers.bmv2"
    # Pipeconfs might contain switch vendor-specific P4 configurations that
    # cannot be made public. For this reason, an URL to the corresponding .oar
    # file must be explicitelly provided.
    pipeconfProvided: false
    pipeconfAppId: "org.onosproject.pipelines.fabric"
